# Generated by Django 5.0 on 2024-01-08 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_title', models.CharField(max_length=150, verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
                'ordering': ['area_title'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=200, verbose_name='Оборудование')),
                ('inventory_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Инвентарный номер')),
                ('factory_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='problems.factoryarea', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField(max_length=2000, verbose_name='Проблема')),
                ('employee_full_name', models.CharField(max_length=150, verbose_name='Ф.И.О. работника')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.equipment', verbose_name='Оборудование')),
                ('factory_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.factoryarea', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='problems.problems', verbose_name='Проблема')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
